### ISSUE TITLE
PHP 7 incompatibility

### ISSUE THREAD

**Issue by sjoerdmaessen** [ianbarber/php-svm#10]
I tried building the extension for PHP 7 without succes however some internals changed with this new version (https://wiki.php.net/phpng-upgrading) which is causing the incompatibility. 

Attached is the log of the failed build process:
[build failed.txt](https://github.com/ianbarber/php-svm/files/54396/build.failed.txt)

**Comment by anhskohbo** [comment]
I have same problem :(

**Comment by sjoerdmaessen** [comment]
@anhskohbo did you found a workaround? I gave up hope to convert the extension to PHP 7 myself.

**Comment by weltling** [comment]
PHP 7.0 compatibility has been fixed in svm 0.2.0 and up.

Thanks.
