### ISSUE TITLE
Wrong prediction

### ISSUE THREAD

**Issue by sebastien-fauvel** [ianbarber/php-svm#7]
I'm not sure whether it's an issue with the php extension or with libsvm itself, or if I just don't understand how libsvm oughts to work... With following code:

``` php
<?php

$trainingData = array(
    array(-1, 1 => 0.45),
    array(-1, 1 => 0.50),
    array(+1, 1 => 0.55),
);

$testData = array(1 => 0.55);

$svm = new SVM();
$svmModel = $svm->train($trainingData);

var_dump($svmModel->predict($testData));
```

I would expect to get `+1` as a prediction, since the test data has been associated with this category in the training. But I get the following instead:

``` bash
*
optimization finished, #iter = 1
nu = 0.666667
obj = -1.997503, rho = -0.995025
nSV = 2, nBSV = 2
Total nSV = 2
double(-1)
```

It actually looks like I get `-1` as a prediction for _any_ test data.
For information, the trained model is being saved as:

``` bash
vm_type c_svc
kernel_type rbf
gamma 1
nr_class 2
total_sv 2
rho -0.995025
label -1 1
nr_sv 1 1
SV
1 1:0.5 
-1 1:0.55 
```

Now if I drop the first training `array(-1, 1 => 0.45)`, it works as expected:

``` bash
*
optimization finished, #iter = 1
nu = 1.000000
obj = -1.997503, rho = 0.000000
nSV = 2, nBSV = 2
Total nSV = 2
double(1)
```

In that case, the model is being saved as:

``` bash
vm_type c_svc
kernel_type rbf
gamma 1
nr_class 2
total_sv 2
rho 0
label -1 1
nr_sv 1 1
SV
1 1:0.5 
-1 1:0.55 
```

Do you have any explanation for that? It looks like it is related to the `rho` value?

**Comment by ratihayu** [comment]
@sebastien-fauvel can you please tell me how to get optimal weight and scale the data in php?

**Comment by sjoerdmaessen** [comment]
@ratihayu the most important part is to understand your dataset first. I personally noticed I don't have to specify weights in most cases as long as my dataset is well balanced. It depends on the features you are working with. Could you supply an example?
Scaling on the other hand is always needed to get decent results. If you know the min and max values of your feature value it can be easy as this: [https://github.com/sjoerdmaessen/machinelearning/blob/master/src/Feature/Preprocessor/Scale.php](https://github.com/sjoerdmaessen/machinelearning/blob/master/src/Feature/Preprocessor/Scale.php) if you don't know the exact maximum value you could map the values to categories and use the categories as values. Again this all depends on the dataset / features you are working with. Good luck!

**Comment by ratihayu** [comment]
@sjoerdmaessen here's my dataset http://13.76.92.195/ta/Klasifikasi/csv. I got a poor result in cross-validation: 0.44155844155844. I train my data with the default parameters from LibSVM PHP.
Thank you for the scaling example!

The [guide](http://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf) is actually very helpful, but I can't find how to get the best C and γ parameters from cross-validation

**Comment by sjoerdmaessen** [comment]
By taking a quick look at your example dataset it seems you are trying to perform regression rather then classification. (index0 variations: 3,4,5,6,7,8,10,11,13,14,15,16,17,18,20,21,22). Is that correct?

**Comment by ratihayu** [comment]
I'm using SVM for classification, the index 0 variations are the class labels. I'm trying to build SVM model by training my data train set then I can predict which class is my new data test.

**Comment by ratihayu** [comment]
@sjoerdmaessen I'm using SVM for classification, the index 0 variations are the class labels. I'm trying to build SVM model by training my data train set then I can predict which class is my new data test.

**Comment by sjoerdmaessen** [comment]
Well considering you have this amount of different classes and only a small dataset a good first step would be to apply a one-versus-all method. Where you classify class 3 as 0 and all the other classes as 1. Cross validate the result and see if that gives better performance... repeat for the other classes. Especially with this amount of classes multiclass classification can become very difficult with such a small dataset.

**Comment by ratihayu** [comment]
@sjoerdmaessen I planned to enlarge my dataset, but I doubt it would give me the higher result of accuracy because I only train and predict using the default parameters of LibSVM.
This [guide](http://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf) tells me some procedure to gained more accuracy:
![image](https://cloud.githubusercontent.com/assets/11593529/15804780/b4f3fbfa-2b3e-11e6-94da-c717370f9d72.png)
But I can't find how to get the best C and γ parameters from cross-validation (Step 5) and how to use those parameters (Step 6).

**Comment by sjoerdmaessen** [comment]
Please check out: [https://github.com/cjlin1/libsvm/tree/master/tools](https://github.com/cjlin1/libsvm/tree/master/tools). But I still suggest applying the one-versus-all method before running.

**Comment by ratihayu** [comment]
@sjoerdmaessen thank you! You're a big help.

**Comment by ratihayu** [comment]
@sjoerdmaessen can I ask about the one-versus-all approach? How do you do one-versus-all method in LibSVM for PHP? Because there's no documentation for it.
